stages:
  - GetCounterData

GetCounterData:
  image: "python:3.7"
  stage: GetCounterData
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$GIT_SSH_PRIV_KEY")
    - git config --global user.email "todor@camplight.net"
    - git config --global user.name "Gitlab Runner"
    - mkdir -p ~/.ssh
    - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - apt-get update -qy
    - pip install python-gitlab
    - python --version
    - python src/scripts/scrapper.py
    - git remote rm origin && git remote add origin "git@gitlab.com:jcole2/c-combinator.git"
    - git commit -a -m "Commit message here :) [skip ci]" || echo "No changes, nothing to commit!"
    - git push origin HEAD:$CI_COMMIT_REF_NAME
